add react-touter-dom
jeje59223/video-games--frontend pull request #8
Opened 2022-05-05 20:02 UTC by jeje59223

2022-05-10 16:03 UTC, Jupoulet requested changes

2022-05-10 16:03 UTC, Jupoulet commented on src/components/molecules/NavBar/NavBar.tsx
> +                            </a>
Tu dois te servir des composants react router dom pour faire tes redirections. https://reactrouter.com/docs/en/v6/getting-started/overview#navigation

En mettant des balises <a> tu casses le principe de SPA (Single Page Application), et tu vas surtout forcer ton site à reload complètement et à retélécharger tout ton bundle JS (ce que l'on souhaite faire une seule fois dans ce genre d'app car c'est une opération couteuse et frustrante pour l'utilisateur)

2022-05-10 16:03 UTC, Jupoulet commented on src/components/templates/home-template/HomeTemplate.tsx
> +            <h1 className="HomeTemplate-title" data-testid="video-games-catalog">
Je ne te vois pas te servir de ton data-testid dans un test ou ailleurs dans ton app c'est un oubli ?

2022-05-10 16:17 UTC, jeje59223 commented on src/components/molecules/NavBar/NavBar.tsx
> +                            </a>
Ah oui faut que j'utilise <Link></Link> 🙂

2022-05-10 16:18 UTC, jeje59223 commented on src/components/templates/home-template/HomeTemplate.tsx
> +            <h1 className="HomeTemplate-title" data-testid="video-games-catalog">
Je l'utilise dans src/App.test.tsx

2022-05-10 16:18 UTC, jeje59223 commented
<img width="586" alt="Capture d’écran 2022-05-10 à 18 18 24" src="https://user-images.githubusercontent.com/47606138/167675618-aae945ae-1a84-438f-b361-531aa164971f.png">

2022-05-11 07:54 UTC, florentbarriol commented on src/components/templates/home-template/HomeTemplate.tsx
> +                Welcome in your <strong style={{ color: '#494949' }}>Video Games Catalog</strong>
Je crois qu'on te l'a déjà indiqué dans la précédente revue : Essaie de ne jamais utiliser de style css inline

2022-05-11 07:54 UTC, florentbarriol commented on src/App.tsx
> +
suggestion: mettre en commun les valeurs des path de chaque Route avec ton tableau `pages` dans `NavBar`.
Tu peux créer un tableau avec toutes les infos dont tu as besoin dans la `NavBar` et pour tes `Route`

2022-05-16 07:24 UTC, florentbarriol commented on src/App.tsx
> +    { path: pages[3].url, element: pages[3].element },
Je te conseille d'utiliser une fonction `.map` sur `pages` pour passer de la structure de `pages` à ton tableau pour `useRoutes`.
`[{ url:'xxx', element: 'Component'},...] => [{ path:'xxx', element: 'Component'},...] `
Ce sera moins source d'erreur que d'accèder au tableau à la main comme tu as fait.
Car c'est ta "machine" qui fait le boulot à ta place :p

2022-05-16 10:15 UTC, jeje59223 commented on src/App.tsx
> +    { path: pages[3].url, element: pages[3].element },
J'ai corrigé 🙂 merci pour les retours

2022-06-10 19:34 UTC, merged